spring.application.name=student-management
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/student_management}
server.port=8080
app.jwt.secret=A5IPppwXqWE1bOYnKVrHjk66oWsMA5pJQnuk07rr/ug
app.jwt.expiration-ms=86400000